Gh 8
BMSTU-ICS-CS-2019/i3000 pull request #17
Opened 2022-05-27 18:35 UTC by DmitryKersh

2022-05-28 20:36 UTC, aaaaaaaalesha approved these changes

2022-05-28 20:36 UTC, aaaaaaaalesha commented on components/589IR12/sources/589IR12/model.cpp
> +    }
m?

2022-05-29 15:50 UTC, DmitryKersh commented on components/589IR12/sources/589IR12/model.cpp
> +    }
ну если MD=1 это режим вывода и менять ничего не надо

2022-05-29 16:40 UTC, JarvisCraft requested changes

2022-05-29 16:40 UTC, JarvisCraft commented on components/589IR12/include/589IR12/model.hpp
> +    static VOID SET_STATE(bool condition, IDSIMPIN2 *pin, ABSTIME time);
Нафига?

2022-05-29 16:40 UTC, JarvisCraft commented on components/589IR12/sources/589IR12/model.cpp
> +    BOOL SELECTED = islow(_pin_CS1->getstate()) && ishigh(_pin_CS2->getstate());
Ренеймни

2022-05-29 16:40 UTC, JarvisCraft commented on components/589IR12/sources/589IR12/model.cpp
> +    if (ishigh(_pin_MD->getstate())) {
В одну строчку мержни

2022-05-29 16:41 UTC, JarvisCraft requested changes

2022-05-29 16:41 UTC, JarvisCraft commented on components/CMakeLists.txt
> +add_subdirectory(589IR12)
Порядок

2022-05-29 17:07 UTC, JarvisCraft submitted a review, later dismissed

2022-05-29 18:24 UTC, JarvisCraft approved these changes

2022-05-29 18:24 UTC, merged