feat(GH-5): implement no-op 589IK02 component
BMSTU-ICS-CS-2019/i3000 pull request #7
Opened 2022-05-10 11:42 UTC by aaaaaaaalesha

2022-05-11 02:24 UTC, aaaaaaaalesha commented on components/589IK02/sources/589IK02/model.cpp
> +    if (_pin_CLK->isposedge()) { // Ucc maybe?
Возможно здесь нужна проверка напряжения питания...
а может API автоматически подразумевает, что при `Ucc < необходимого для питания`, функция `simulate` "спит"

2022-05-11 02:24 UTC, aaaaaaaalesha commented on components/589IK02/sources/589IK02/model.cpp
> +}
Я ВАМ ЗАПРЕЩАЮ!

2022-05-11 02:24 UTC, aaaaaaaalesha commented on components/589IK02/include/589IK02/model.hpp
> +    static UINT TO_UINT(IDSIMPIN* p);
над подумать, как избежать нагромождения методов этих
мб передавать аргументом кортеж, а в реализации, итерируясь с конца, формировать `UINT` 🤔

2022-05-22 17:31 UTC, aaaaaaaalesha commented on components/589IK02/include/589IK02/model.hpp
> +    static UINT TO_UINT(IDSIMPIN* p);
суп
 с ним

2022-05-27 18:49 UTC, DmitryKersh approved these changes
ПОЛУЧШЕ, НО ТОЖ ХУЙНЯ

2022-05-27 20:11 UTC, JarvisCraft requested changes

2022-05-27 20:11 UTC, JarvisCraft commented on components/589IK02/sources/589IK02/model.cpp
> +    condition ? pin->setstate(time, details::DELAY, SHI) : pin->setstate(time, details::DELAY, SLO);
Занеси, пожалуйста, тернарный оператор внутрь: `condition ? SHI : SLO`

2022-05-27 20:38 UTC, DmitryKersh commented on components/589IK02/sources/589IK02/model.cpp
> +    condition ? pin->setstate(time, details::DELAY, SHI) : pin->setstate(time, details::DELAY, SLO);
O, я так написал? Видать очень уставший был...

2022-05-29 10:06 UTC, closed without merging